export const AUTH_COOKIE_SETTINGS = Symbol("AUTH_COOKIE_SETTINGS");
export const AUTH_RATE_LIMITER = Symbol("AUTH_RATE_LIMITER");
export const AUTH_SERVICE = Symbol("AUTH_SERVICE");
export const AUTH_STORE = Symbol("AUTH_STORE");
export const CHECKOUT_SERVICE = Symbol("CHECKOUT_SERVICE");
export const CHECKOUT_STORE = Symbol("CHECKOUT_STORE");
export const DATABASE_HEALTH = Symbol("DATABASE_HEALTH");
export const PAYMENT_GATEWAY = Symbol("PAYMENT_GATEWAY");
export const PAYMENT_WEBHOOKS_SERVICE = Symbol("PAYMENT_WEBHOOKS_SERVICE");
export const PAYMENTS_SIMULATION_SERVICE = Symbol(
  "PAYMENTS_SIMULATION_SERVICE"
);
export const DISCOVERY_SERVICE = Symbol("DISCOVERY_SERVICE");
export const DISCOVERY_STORE = Symbol("DISCOVERY_STORE");
export const EVENTS_SERVICE = Symbol("EVENTS_SERVICE");
export const EVENTS_STORE = Symbol("EVENTS_STORE");
export const HOLD_EXPIRY_MIRROR = Symbol("HOLD_EXPIRY_MIRROR");
export const HOLDS_SERVICE = Symbol("HOLDS_SERVICE");
export const HOLDS_STORE = Symbol("HOLDS_STORE");
export const ORGANIZATIONS_SERVICE = Symbol("ORGANIZATIONS_SERVICE");
export const ORGANIZATIONS_STORE = Symbol("ORGANIZATIONS_STORE");
export const REDIS_HEALTH = Symbol("REDIS_HEALTH");
export const STRUCTURED_LOGGER = Symbol("STRUCTURED_LOGGER");
export const VENUES_SERVICE = Symbol("VENUES_SERVICE");
export const VENUES_STORE = Symbol("VENUES_STORE");
