import type { QueryResultRow } from "pg";

import { hashAuthSecret } from "./auth.js";
import type { TicketTypeKind } from "./events.js";
import { resolveActorKey, type OrderActor } from "./orders.js";
import type { DatabaseExecutor } from "./outbox.js";

export type TicketStatus = "active" | "checked_in" | "void" | "refunded";

/**
 * One admission credential as its owner may see it. Carries the nonsecret
 * public number, event and access details, and rotation state - never the QR
 * token hash and never a raw bearer.
 */
export interface TicketAccessRecord {
  eventEndsAt: Date | null;
  eventId: string;
  eventStartsAt: Date | null;
  eventStatus: string;
  eventTimezone: string;
  eventTitle: string;
  id: string;
  orderId: string;
  orderPublicNumber: string;
  publicNumber: string;
  /** Null until the owner first mints a usable QR bearer. */
  qrRotatedAt: Date | null;
  rowLabel: string | null;
  seatAccessible: boolean | null;
  seatLabel: string | null;
  sectionName: string | null;
  status: TicketStatus;
  ticketTypeKind: TicketTypeKind;
  ticketTypeName: string;
  venueDescription: string | null;
  venueName: string;
}

export class TicketNotFoundError extends Error {
  constructor() {
    super("The ticket does not exist.");
    this.name = "TicketNotFoundError";
  }
}

interface TicketAccessRow extends QueryResultRow, TicketAccessRecord {}

const ticketColumns = `
  tk."id",
  tk."public_number" AS "publicNumber",
  tk."status",
  tk."qr_rotated_at" AS "qrRotatedAt",
  tk."order_id" AS "orderId",
  o."public_number" AS "orderPublicNumber",
  e."id" AS "eventId",
  e."title" AS "eventTitle",
  e."timezone" AS "eventTimezone",
  e."starts_at" AS "eventStartsAt",
  e."ends_at" AS "eventEndsAt",
  e."status" AS "eventStatus",
  v."name" AS "venueName",
  v."description" AS "venueDescription",
  t."name" AS "ticketTypeName",
  t."kind" AS "ticketTypeKind",
  s."section_name" AS "sectionName",
  s."row_label" AS "rowLabel",
  s."seat_label" AS "seatLabel",
  s."accessible" AS "seatAccessible"
`;

const ticketJoins = `
  FROM "tickets" tk
  JOIN "orders" o ON o."id" = tk."order_id"
  JOIN "events" e ON e."id" = tk."event_id"
  JOIN "venues" v ON v."id" = e."venue_id"
  JOIN "ticket_types" t ON t."id" = tk."ticket_type_id"
  LEFT JOIN "event_seats" s ON s."id" = tk."event_seat_id"
`;

/** Lists every ticket owned by the actor, newest order first. */
export async function listTicketsForActor(
  executor: DatabaseExecutor,
  input: { actor: OrderActor }
): Promise<TicketAccessRecord[]> {
  const actorKey = resolveActorKey(input.actor);
  const result = await executor.query<TicketAccessRow>(
    `SELECT ${ticketColumns}
     ${ticketJoins}
     WHERE o."actor_key" = $1
     ORDER BY o."created_at" DESC, tk."public_number" ASC`,
    [actorKey]
  );
  return result.rows;
}

/** Loads one actor-scoped ticket; the actor never sees another actor's ticket. */
export async function loadTicketForActor(
  executor: DatabaseExecutor,
  input: { actor: OrderActor; ticketId: string }
): Promise<TicketAccessRecord> {
  const actorKey = resolveActorKey(input.actor);
  const result = await executor.query<TicketAccessRow>(
    `SELECT ${ticketColumns}
     ${ticketJoins}
     WHERE tk."id" = $1 AND o."actor_key" = $2`,
    [input.ticketId, actorKey]
  );
  const row = result.rows[0];
  if (!row) {
    throw new TicketNotFoundError();
  }
  return row;
}

export type RotateTicketOutcome =
  /** A fresh bearer was minted; the prior one no longer matches. */
  | { outcome: "rotated"; publicNumber: string; rotatedAt: Date }
  /** The ticket is not active, so it holds no redeemable credential. */
  | { outcome: "not_active"; status: TicketStatus };

/**
 * Rotates an active ticket's QR credential: stores the SHA-256 hash of a fresh
 * 256-bit bearer and stamps the rotation time, atomically invalidating the
 * prior bearer. The raw token is generated by the caller and never persisted;
 * only its hash reaches this function. Returns not_active when the ticket
 * exists for the actor but cannot carry a live credential (already void).
 */
export async function rotateTicketQrToken(
  executor: DatabaseExecutor,
  input: { actor: OrderActor; ticketId: string; tokenHash: string }
): Promise<RotateTicketOutcome> {
  const actorKey = resolveActorKey(input.actor);
  const updated = await executor.query<
    { publicNumber: string; rotatedAt: Date } & QueryResultRow
  >(
    `UPDATE "tickets" tk
     SET "qr_token_hash" = $3, "qr_rotated_at" = CURRENT_TIMESTAMP
     FROM "orders" o
     WHERE tk."id" = $1
       AND o."id" = tk."order_id"
       AND o."actor_key" = $2
       AND tk."status" = 'active'
     RETURNING tk."public_number" AS "publicNumber",
               tk."qr_rotated_at" AS "rotatedAt"`,
    [input.ticketId, actorKey, input.tokenHash]
  );
  const row = updated.rows[0];
  if (row) {
    return {
      outcome: "rotated",
      publicNumber: row.publicNumber,
      rotatedAt: row.rotatedAt,
    };
  }

  // No active row moved: either the actor does not own it (surface as absent)
  // or it exists but is void. A void-status read distinguishes the two.
  const existing = await loadTicketForActor(executor, {
    actor: input.actor,
    ticketId: input.ticketId,
  });
  return { outcome: "not_active", status: existing.status };
}

/** Hashes a raw QR bearer for storage or comparison; never store the raw value. */
export function hashQrToken(token: string): string {
  return hashAuthSecret(token);
}
